/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAiInsightsRouteImport } from './routes/_app/ai-insights'
import { Route as AppCandidatesRouteImport } from './routes/_app/candidates'
import { Route as AppInterviewsRouteImport } from './routes/_app/interviews'
import { Route as AppJobsRouteImport } from './routes/_app/jobs'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAiInsightsRoute = AppAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesRoute = AppCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewsRoute = AppInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/ai-insights': typeof AppAiInsightsRoute
  '/candidates': typeof AppCandidatesRoute
  '/interviews': typeof AppInterviewsRoute
  '/jobs': typeof AppJobsRoute
}
export interface FileRoutesByTo {
  '/ai-insights': typeof AppAiInsightsRoute
  '/candidates': typeof AppCandidatesRoute
  '/interviews': typeof AppInterviewsRoute
  '/jobs': typeof AppJobsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/ai-insights': typeof AppAiInsightsRoute
  '/_app/candidates': typeof AppCandidatesRoute
  '/_app/interviews': typeof AppInterviewsRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-insights' | '/candidates' | '/interviews' | '/jobs'
  fileRoutesByTo: FileRoutesByTo
  to: '/ai-insights' | '/candidates' | '/interviews' | '/jobs' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/ai-insights'
    | '/_app/candidates'
    | '/_app/interviews'
    | '/_app/jobs'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-insights': {
      id: '/_app/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AppAiInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidates': {
      id: '/_app/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof AppCandidatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interviews': {
      id: '/_app/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof AppInterviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiInsightsRoute: typeof AppAiInsightsRoute
  AppCandidatesRoute: typeof AppCandidatesRoute
  AppInterviewsRoute: typeof AppInterviewsRoute
  AppJobsRoute: typeof AppJobsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiInsightsRoute: AppAiInsightsRoute,
  AppCandidatesRoute: AppCandidatesRoute,
  AppInterviewsRoute: AppInterviewsRoute,
  AppJobsRoute: AppJobsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
